### ISSUE TITLE
주피터 노트북 수정 요청 - 기훈

### ISSUE THREAD

**Issue by raymin0223** [Lee-Gihun/LG_VisionModule3#1]
- data path와 weight path 정리 필요.

- 데이터셋 구성 파트는 Augmentation 부분만 문제로 만들면 좋아보임.

- EfficientNet 모델 부분에서 설명과 코드가 일치하지 않는 부분이 있음.
ex) mid, end 사용 부분이 설명과 일치하지 않음.

- EfficientNet freeze하는 parameter에 대한 rule이 다소 의아해 끝부분을 빼곤 모두 적용하면 좋을 것 같음.

- [05]-모델 만들기 3 부분 설명에서 tensor shape 설명이 잘못된 부분이 있음.

- [07]-Prior Box 만들기 부분에서 cx, cy, h, w의 설명이 누락되어 있음. 또한 코드 내에서 잘못된 것 같은 부분들이 있음.
ex) (i+0.5) / feature_dims[fmap], sqrt(ratio)

- [08]-손실함수 설정하기 부분에서 find_jaccard 함수 설명이 추가되면 좋아보임. 또한 confidence loss에서 n_positive로만 나눠주는 부분이 관용적인 것인지 의문.

-  [08]-손실함수 설정하기 코드가 꼭 필요한데, 이해하는게 조금은 어려워보임.

- [10]번 노트북에서 './est_199_1.378.pth' weights가 없는 에러가 발생.

- [11]번 노트북에서의 설정된 weight와 ssd_detect 함수가 잘못 설정된 것으로 보임.

**Comment by Lee-Gihun** [comment]
- [x] ~data path와 weight path 정리 필요.~
- datapath는 abs path 기준으로 설정되므로 문제없이 작동하는 것을 확인. 파일 저장 딜레이 때문인 것 같아서 script에 sleep 3초씩 추가.
- weight path에 대해서 shell script하나 더 추가함.
- [x] ~데이터셋 구성 파트는 Augmentation 부분만 문제로 만들면 좋아보임.~
- 데이터셋 구성 자체는 batch를 받을 때 뭐가 나오는지 알려주기 위해서 필요하다고 생각함.
- collate_fn을 쓰는건 (Optional)로 표기해서, 참가자들에게 직접 시키지 않고 같이 빈칸을 채우면서 왜 필요한지만 설명하는 것으로 수정함.
- [x] ~EfficientNet 모델 부분에서 설명과 코드가 일치하지 않는 부분이 있음.~
~ex) mid, end 사용 부분이 설명과 일치하지 않음.~
- 수정 완료
- [x] ~EfficientNet freeze하는 parameter에 대한 rule이 다소 의아해 끝부분을 빼곤 모두 적용하면 좋을 것 같음.~
- 이건 그대로 유지. 의아할 수 있는 부분에서 어디까지 freeze 할지의 여부에 대해서 고민하고 discussion하는 것까지가 실습에 포함되어있음.

- [x] ~[05]-모델 만들기 3 부분 설명에서 tensor shape 설명이 잘못된 부분이 있음.~
- 수정 완료
- [x] ~[07]-Prior Box 만들기 부분에서 cx, cy, h, w의 설명이 누락되어 있음. 또한 코드 내에서 잘못된 것 같은 부분들이 있음.~
- ~ex) (i+0.5) / feature_dims[fmap], sqrt(ratio)~
- 잘못된 부분은 아니었는데 Definition이 제대로 제공되지 않아서 내용을 알기가 어려웠음. cx, cy에 대한 설명과 함께 해당 부분에 대한 설명을 ppt 설명자료로 보완함.

- [x] ~[08]-손실함수 설정하기 부분에서 find_jaccard 함수 설명이 추가되면 좋아보임. 또한 confidence loss에서 n_positive로만 나눠주는 부분이 관용적인 것인지 의문.~
- jaccard index (Intersection of Union)에 대한 설명을 ppt 파일에 추가함. confidence_loss의 경우, Localization Loss가 (n_positives에 대해서만 연산되기 때문에) n_positive로 나눠지므로, 균형을 맞춰준다는 의미에서 n_positive를 적용함. 관용적인것 맞음.

- [x] ~[08]-손실함수 설정하기 코드가 꼭 필요한데, 이해하는게 조금은 어려워보임.~
- 최대한 step by step으로 설명하기 위해서 ppt 설명자료를 상세히 제작함. 코드 이해보다도 concept 이해에 중점을 맞춰서 교육을 진행하도록 할 예정.

- [x] ~[10]번 노트북에서 './test_199_1.378.pth' weights가 없는 에러가 발생.~
- 에러가 아님. 9번 notebook을 완성하고 실행하면 학습된 weight가 저장되는데, 그걸 10번에서 불러오는 것임.

- [x] ~[11]번 노트북에서의 설정된 weight와 ssd_detect 함수가 잘못 설정된 것으로 보임.~
- weight는 정상이었음. ssd_detect의 argument인 weapon을 False로 설정하면 원래 class에 대해 예측함. binary detection에 대응하기 위해서 요렇게 짜놓음.

**Comment by Lee-Gihun** [comment]
확인하고 close 해주세요~

**Comment by raymin0223** [comment]
굳뜨!
